### ISSUE TITLE
Crash when holding shift

### ISSUE THREAD

**Issue by flimblet** [mortuusars/Exposure#46] opened 2024-02-14 21:03 UTC
Always when I got the camera equipped, if I press shift, the game freezes, and then crashes.

Crash log:

[crash-2024-02-14_18.01.24-client.txt](https://github.com/mortuusars/Exposure/files/14288554/crash-2024-02-14_18.01.24-client.txt)

**Comment by mortuusars** [comment] 2024-02-14 22:21
Duplicate of https://github.com/mortuusars/Exposure/issues/19

**Closed as duplicate by mortuusars** 2024-02-14 22:21 UTC
Labels: duplicate
