### ISSUE TITLE
Error when developing film in the photo lab.

### ISSUE THREAD

**Issue by EntrGame** [mortuusars/Exposure#107] opened 2024-07-20 08:06 UTC
![image](https://github.com/user-attachments/assets/dc989f0e-6d1b-4659-8626-490240c6a777)

Mods:
  [✔️] (Fabric)MoreBeeInfo-1.20-1.1.1.jar
  [✔️] AdaptiveTooltips-1.3.0-fabric-1.20.2.jar
  [✔️] AdvancementPlaques-1.20.1-fabric-1.4.11.jar
  [✔️] amendments-1.20-1.1.13-fabric.jar
  [✔️] antique-atlas-2.9.12+1.20.jar
  [✔️] Aquamirae-6.jar
  [✔️] archers-1.2.4+1.20.1.jar
  [✔️] architectury-9.2.14-fabric.jar
  [✔️] atrium-0.1.1.jar
  [✔️] Axiom-3.2.1-for-MC1.20.1.jar
  [✔️] azurelibarmor-fabric-1.20.1-2.0.3.jar
  [✔️] azurelib-fabric-1.20.1-2.0.25.jar
  [✔️] bendy-lib-fabric-4.0.0.jar
  [✔️] bettercombat-fabric-1.8.4+1.20.1.jar
  [✔️] BetterPingDisplay-Fabric-1.20.1-1.1.1.jar
  [✔️] Boids-1.2.2.jar
  [✔️] BOMD-1.7.5-1.20.1.jar
  [✔️] bounced-1.20-3.2.0.jar
  [✔️] c2me-fabric-mc1.20.1-0.2.0+alpha.11.5.jar
  [✔️] CerbonsAPI-Fabric-1.20.1-1.1.0.jar
  [✔️] chatanimation-1.0.5.jar
  [✔️] CITResewn-1.1.3+1.20.jar
  [✔️] clifftree-1.1.jar
  [✔️] cloth-config-11.1.118-fabric.jar
  [✔️] combatroll-fabric-1.3.1+1.20.1.jar
  [✔️] CustomSkinLoader_Fabric-14.19.1.jar
  [✔️] dark-loading-screen-1.6.14.jar
  [✔️] doapi-1.2.8-fabric.jar
  [✔️] dummmmmmy-1.20-1.8.14-fabric.jar
  [✔️] dungeon_difficulty-2.1.0+1.20.1.jar
  [✔️] dungeons+-1.8.4b.jar
  [✔️] dynamiclights-v1.7.1-mc1.17x-1.20x-mod.jar
  [✔️] ecologics-fabric-1.20.1-2.2.0.jar
  [✔️] enhancedblockentities-0.9+1.20.jar
  [✔️] entity_model_features_fabric_1.20.1-2.1.3.jar
  [✔️] entity_texture_features_fabric_1.20.1-6.1.3.jar
  [✔️] entityculling-fabric-1.6.5-mc1.20.1.jar
  [✔️] epicsamurai-fabric-0.0.3-beta.jar
  [✔️] exordium-fabric-1.2.1-mc1.20.1.jar
  [✔️] explosive-enhancement-1.2.2-1.20.x.jar
  [✔️] exposure-1.20.1-1.7.3-fabric.jar
  [✔️] fabric-api-0.92.2+1.20.1.jar
  [✔️] fabric-chunkpregen-0.3.7.jar
  [✔️] fabric-language-kotlin-1.10.9+kotlin.1.9.0.jar
  [✔️] FarmersDelight-1.20.1-2.0.16+refabricated.jar
  [✔️] Farmersrespite-Fabric-3.0.0.jar
  [✔️] ferritecore-6.0.1-fabric.jar
  [✔️] ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric (1).jar
  [✔️] forgotten_temples-1.0.0-1.20.1.jar
  [✔️] forsaken_corpses_1.1.0_1.20.1.jar
  [✔️] funky-flora-1.5.jar
  [✔️] geckolib-fabric-1.20.1-4.2.4.jar
  [✔️] geophilic-v2.1.0-mc1.20u1.20.2.jar
  [✔️] held-item-info-1.5.0.jar
  [✔️] HorseExpert-v8.1.1-1.20.1-Fabric.jar
  [✔️] horse-stonks-1.0.1.jar
  [✔️] Iceberg-1.20.1-fabric-1.1.18.jar
  [✔️] immersive_melodies-0.1.0+1.20.1-fabric.jar
  [✔️] indium-1.0.30+mc1.20.4.jar
  [✔️] InvMove-1.20-0.8.4-Fabric.jar
  [✔️] iris-1.7.0+mc1.20.1.jar
  [✔️] ItemBorders-1.20.1-fabric-1.2.0.jar
  [✔️] ivespoken-2.1.0-fabric1.20.jar
  [✔️] Jewelry-1.3.4+1.20.1.jar
  [✔️] Kiwi-1.20.1-fabric-11.5.4.jar
  [✔️] Ksyxis-1.2.2.jar
  [✔️] language-reload-1.5.7+1.20.jar
  [✔️] letsdo-API-fabric-1.2.9-fabric.jar
  [✔️] letsdo-brewery-fabric-1.1.5.jar
  [✔️] letsdo-nethervinery-fabric-1.2.9.jar
  [✔️] letsdo-vinery-fabric-1.4.14.jar
  [✔️] lithium-fabric-mc1.20.1-0.11.2.jar
  [✔️] mcde-1.5.7-1.20.jar
  [✔️] memoryleakfix-fabric-1.17+-1.1.5.jar
  [✔️] modelfix-1.14-fabric.jar
  [✔️] modmenu-7.2.1.jar
  [✔️] moonlight-1.20-2.11.9-fabric.jar
  [✔️] morechathistory-1.19.1-1.1.1.jar
  [✔️] moremobvariants-fabric+1.20-1.2.2.jar
  [✔️] mru-0.4.0+1.20.jar
  [✔️] netherite_horse_armor-fabric-1.20.1-1.0.4.jar
  [✔️] NethersDelight-Refabricated-1.20.1-4.0.3.jar
  [✔️] niftycarts-3.0.11.20.1.jar
  [✔️] NoChatReports-FABRIC-1.20.1-v2.2.2.jar
  [✔️] notenoughanimations-fabric-1.7.2-mc1.20.1.jar
  [✔️] not-just-biomes-mc1.20-1.1.0.jar
  [✔️] nyfsspiders-fabric-1.20.1-2.1.1.jar
  [✔️] Obscure-API-16.jar
  [✔️] ok-boomer-0.1.3+1.20.jar
  [✔️] owo-lib-0.11.2+1.20.jar
  [✔️] paladins-1.2.6+1.20.1.jar
  [✔️] particle-rain-2.0.7.jar
  [✔️] PickUpNotifier-v8.0.0-1.20.1-Fabric.jar
  [✔️] player-animation-lib-fabric-1.0.2-rc1+1.20.jar
  [✔️] Prism-1.20.1-fabric-1.0.5.jar
  [✔️] profundis-1.6.2.jar
  [✔️] projectile_damage-fabric-3.2.3+1.20.1.jar
  [✔️] PuzzlesLib-v8.1.18-1.20.1-Fabric.jar
  [✔️] ranged_weapon_api-1.1.2+1.20.1.jar
  [✔️] realisticsleep-1.10.2+mc1.20-1.20.1.jar
  [✔️] reeses_sodium_options-1.7.2+mc1.20.1-build.101.jar
  [✔️] reimaginedmenus-1.1.0-1.20.x.jar
  [✔️] replaymod-1.20.1-2.6.17.jar
  [✔️] rogues-1.0.8+1.20.1.jar
  [✔️] RoughlyEnoughItems-12.0.684-fabric.jar
  [✔️] runes-0.9.13+1.20.1.jar
  [✔️] scholar-1.20.1-1.0.0-fabric.jar
  [✔️] scorchful-0.6.2.jar
  [✔️] shinyhorses-1.0.0.jar
  [✔️] smallships-fabric-1.20.1-2.0.0-b1.0.jar
  [✔️] smokesignals-1.0+1.20.jar
  [✔️] SnowRealMagic-1.20.1-fabric-10.3.1.jar
  [✔️] sodium-extra-0.5.4+mc1.20.1-build.115.jar
  [✔️] sodium-fabric-0.5.8+mc1.20.1.jar
  [✔️] sound-physics-remastered-fabric-1.20.1-1.3.1.jar
  [✔️] spell_engine-0.15.6+1.20.1.jar
  [✔️] spell_power-0.11.0+1.20.1.jar
  [✔️] spelunkery-1.20.1-0.3.4-fabric.jar
  [✔️] starlight-1.1.2+fabric.dbc156f.jar
  [✔️] status-effect-bars-1.0.3-1.20.1.jar
  [✔️] structure_pool_api-1.0+1.20.1.jar
  [❌] Surface-1.5-1.20.1.jar.disabled (disabled)
  [✔️] Surface-1.8.1-1.20.1.jar
  [✔️] surveyor-0.6.11+1.20.jar
  [❌] TerraBlender-fabric-1.20.1-3.0.1.2.jar.disabled (disabled)
  [✔️] TerraBlender-fabric-1.20.1-3.0.1.7.jar
  [✔️] thaumon-fabric-2.1.0+1.20.1.jar
  [✔️] thermoo-2.3.1.jar
  [✔️] tia-1.20-1.1-fabric.jar
  [✔️] TreeChop-1.20.1-fabric-0.18.8.jar
  [✔️] trinkets-3.7.2.jar
  [✔️] valhelsia_core-fabric-1.20.1-1.1.1.jar
  [✔️] valhelsia_furniture-fabric-1.20.1-1.1.2.jar
  [✔️] vc_gliders-fabric-1.1.5.jar
  [✔️] vcinteraction-fabric-1.20.1-1.0.6.jar
  [✔️] vectorientation-1.0.1a-1.20.jar
  [✔️] villagesandpillages-fabric-mc1.20.1-1.0.0.jar
  [✔️] VisualWorkbench-v8.0.0-1.20.1-Fabric.jar
  [✔️] voicechat-fabric-1.20.1-2.5.19.jar
  [✔️] wetlands-1.2-1.20.1.jar
  [✔️] wizards-1.2.2+1.20.1.jar
  [✔️] yet-another-config-lib-fabric-3.2.2+1.20.jar
  [✔️] youwereslain-1.0.0-1.20.x.jar
  [✔️] YungsApi-1.20-Fabric-4.0.2.jar

**Comment by mortuusars** [comment] 2024-07-20 08:13
Duplicate of #106

**Closed as completed by mortuusars** 2024-07-20 08:13 UTC
