### ISSUE TITLE
Chromatic photograph

### ISSUE THREAD

**Issue by PlagueDoctor0049** [mortuusars/Exposure#103] opened 2024-07-18 19:15 UTC
I can't print chromatic photo. I make 3 frames with red blue and green filters but in lightroom I can only print red chromatic sheet even when i choose green or blue frame. With film from chests it doesn't work too, please help me
![Screenshot_1](https://github.com/user-attachments/assets/cb8470ad-8a9d-43bc-a6c2-4e6521ef51c4)
![Screenshot_2](https://github.com/user-attachments/assets/489cf0eb-cfcc-4daf-84f4-6d23a4377829)

**Comment by PlagueDoctor0049** [comment] 2024-07-18 19:19
Game version 1.20.1 tryed with mod version from 1.7.2 to 1.6.0 without any other mods

**Comment by PlagueDoctor0049** [comment] 2024-07-18 19:20
Game version 1.20.1 tryed with mod version from 1.7.2 to 1.6.0 without any other mods

**Comment by mortuusars** [comment] 2024-07-19 03:03
Duplicate of #92.
Use the sheet as paper for rest of the channels.

**Closed as completed by mortuusars** 2024-07-19 03:03 UTC
